using FluentAssertions;
using System.Text;
using System.Text.Json;

namespace Cblx.Blocks.Json.Tests.RealWorld.Case2;

public class Tests
{
    [Theory]
    [InlineData(_jsonSubject)]
    [InlineData(_jsonSubject2)]
    public async Task Deserializing(string json)
    {
        var stringContent = new StringContent(json, Encoding.UTF8, "application/json");
        var jsonSerializerOptions = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true,
            TypeInfoResolver = JsonContractBuilder.CreateContract()
        };
        jsonSerializerOptions.Converters.Add(new DateOnlyJsonConverter());
        var deserializing = async () => JsonSerializer.DeserializeAsync<Result>(
            await stringContent.ReadAsStreamAsync(),
            jsonSerializerOptions
        );
        await deserializing.Should().NotThrowAsync();
    }

    private const string _jsonSubject = """
        {
          "@odata.context": "https://cdhucrmdev.api.crm2.dynamics.com/api/data/v9.0/$metadataleads(leadid,cdhu_clponmcpf,cdhu_clpococpfconfirmadopordocumento,firstname,cdhu_projeto_origem,cdhu_tipodeatendimento,cdhu_clponmrg,cdhu_clpocorgernourgrne,cdhu_clpocoufrg,cdhu_clpocosexo,cdhu_clponmnomedamae,cdhu_clpodhdatadenascimento,cdhu_clponuidade,cdhu_clponmcidadedenascimento,cdhu_clponmufdenascimento,cdhu_clponmnacionalidade,cdhu_clponmcoreraca,address1_line1,address1_line2,address1_line3,address1_city,address1_stateorprovince,address1_country,address1_addresstypecode,address1_postalcode,_bp_clpo_lk_1opcaomunicipio_value,_bp_clpo_lk_2opcaomunicipio_value,_bp_clpo_lk_3opcaomunicipio_value,bp_clpo_co_1opcaozona,bp_clpo_co_2opcaozona,bp_clpo_co_3opcaozona,cdhu_clpocologradouro,bp_clpopltipodemoradia,bp_clpoittempomoradiaestadosp,bp_clpoittempodemoradiamunicipiosp,emailaddress1,mobilephone,cdhu_clpocomesmoestadocivil,cdhu_clpocoestadocivilatual,cdhu_clpodtcasamentoatual,cdhu_clpocoregimedebensatual,cdhu_clpocosituacao,cdhu_clponmnib,cdhu_clpodtdaalteracaodasituacao,cdhu_clpodtdopactoantenupcialatual,cdhu_clponmlivroatual,cdhu_clponmfolhaatual,cdhu_clpodtdataatual,cdhu_clponmnomedoconjugeatual,cdhu_clponmemailconjugeatual,cdhu_clponmrgdoconjugeatual,cdhu_clponmcpfdoconjugeatual,cdhu_clpocoufdorgdoconjugeatual,cdhu_clpodhdatadenascimentodoconjugeatual,cdhu_clponmnacionalidadedoconjugeatual,cdhu_clpocoprofissaodoconjugeatual,cdhu_clponmnomedamaedoconjugeatual,cdhu_coreracadoconjugeatual,bp_clpoplestadocivildoconjuge,cdhu_clpocograudeinstrucao,bp_clpoplgraudeinstrucaoconj,bp_clpostnomedocompanheirodoconjuge,cdhu_clponmnomesocialapelido,bp_clpobtconfirmacaoveracidadedasinformacoes,cdhu_clpocoprofissaocbo,bp_clpoitquantaspessoastemrenda,bp_clpobtseunucleofamiliarmulheraresponsavel,bp_clpomnsesimqualovalormensaldoaluguel,bp_clpobtalguemdonucleofamiliarpossuideficie,bp_clpobtodeficientevoceseucnjugecompanheiro,bp_clpobtmudancadeconjoucompaposauxilio,bp_clpopltipodedeficiencia,bp_clpobtvoceecadeirante,bp_clpobtnecessidadedeuhadaptada,cdhu_clpocosistemaorigem,bp_clpo_pl_sexodoconjugeatual,bp_clpo_mn_rendadoconjugeatual,cdhu_clpovlvalorrendaatual,bp_cdhu_clponmufdenascimentoconjuge,_cdhu_idunidadehabitacionalid_value,_bp_empreendimentoinscricaoleadid_value,cdhu_data_inicio_auxilio_moradia,bp_clpovloutrarendafamiliar,_bp_clp_lk_conjugeatual_value,_bp_clp_lk_companheiroatual_value,bp_clp_bt_uniaoestavelatual,bp_clp_bt_confirmacaouniaoestavelatual,statecode,cdhu_lead_contact(contactid))",
          "value": [
            {
              "@odata.etag": "W/\u00227089632950\u0022",
              "leadid": "a9a43561-f8ff-ed11-8f6d-002248e05a89",
              "cdhu_clponmcpf": "913.968.597-72",
              "cdhu_clpococpfconfirmadopordocumento": null,
              "firstname": "AARAO LUIZ DA SILVA",
              "cdhu_projeto_origem": "Projeto Cubat\u00E3o",
              "cdhu_tipodeatendimento@OData.Community.Display.V1.FormattedValue": "Atualiza\u00E7\u00E3o Anual",
              "cdhu_tipodeatendimento": 808620000,
              "cdhu_clponmrg": " 22.425.641-5",
              "cdhu_clpocorgernourgrne@OData.Community.Display.V1.FormattedValue": "1 - RG",
              "cdhu_clpocorgernourgrne": 1,
              "cdhu_clpocoufrg@OData.Community.Display.V1.FormattedValue": "SP",
              "cdhu_clpocoufrg": 808620024,
              "cdhu_clpocosexo@OData.Community.Display.V1.FormattedValue": "MASCULINO",
              "cdhu_clpocosexo": 2,
              "cdhu_clponmnomedamae": " ANDREIA ROCHA",
              "cdhu_clpodhdatadenascimento@OData.Community.Display.V1.FormattedValue": "07/10/1966",
              "cdhu_clpodhdatadenascimento": "1966-10-07",
              "cdhu_clponuidade@OData.Community.Display.V1.FormattedValue": "56",
              "cdhu_clponuidade": 56,
              "cdhu_clponmcidadedenascimento": "SAO PAULO",
              "cdhu_clponmufdenascimento": "SP",
              "cdhu_clponmnacionalidade": "BRASILEIRA",
              "cdhu_clponmcoreraca@OData.Community.Display.V1.FormattedValue": "Preta",
              "cdhu_clponmcoreraca": 2,
              "address1_line1": "Jos\u00E9 Mascarenhas, 10",
              "address1_line2": null,
              "address1_line3": "Vila Matilde",
              "address1_city": "SAO PAULO",
              "address1_stateorprovince": "SP",
              "address1_country": "BRASIL",
              "address1_addresstypecode@OData.Community.Display.V1.FormattedValue": "\u00C1rea Urbana",
              "address1_addresstypecode": 1,
              "address1_postalcode": "03515-000",
              "_bp_clpo_lk_1opcaomunicipio_value": null,
              "_bp_clpo_lk_2opcaomunicipio_value": null,
              "_bp_clpo_lk_3opcaomunicipio_value": null,
              "bp_clpo_co_1opcaozona": null,
              "bp_clpo_co_2opcaozona": null,
              "bp_clpo_co_3opcaozona": null,
              "cdhu_clpocologradouro@OData.Community.Display.V1.FormattedValue": "RUA",
              "cdhu_clpocologradouro": 7,
              "bp_clpopltipodemoradia@OData.Community.Display.V1.FormattedValue": "Cedida",
              "bp_clpopltipodemoradia": 2,
              "bp_clpoittempomoradiaestadosp@OData.Community.Display.V1.FormattedValue": "10",
              "bp_clpoittempomoradiaestadosp": 10,
              "bp_clpoittempodemoradiamunicipiosp@OData.Community.Display.V1.FormattedValue": "10",
              "bp_clpoittempodemoradiamunicipiosp": 10,
              "emailaddress1": "testessdsdaasdad@testdadade.com.br",
              "mobilephone": null,
              "cdhu_clpocomesmoestadocivil@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "cdhu_clpocomesmoestadocivil": false,
              "cdhu_clpocoestadocivilatual@OData.Community.Display.V1.FormattedValue": "Casado",
              "cdhu_clpocoestadocivilatual": 1,
              "cdhu_clpodtcasamentoatual@OData.Community.Display.V1.FormattedValue": "05/08/1999",
              "cdhu_clpodtcasamentoatual": "1999-08-05T03:00:00Z",
              "cdhu_clpocoregimedebensatual@OData.Community.Display.V1.FormattedValue": "Comunh\u00E3o Parcial de Bens na Vig\u00EAncia \u00E0 Lei do Div\u00F3rcio n\u00B0 6515/1977",
              "cdhu_clpocoregimedebensatual": 2,
              "cdhu_clpocosituacao@OData.Community.Display.V1.FormattedValue": "Ativo",
              "cdhu_clpocosituacao": 1,
              "cdhu_clponmnib": "656565",
              "cdhu_clpodtdaalteracaodasituacao@OData.Community.Display.V1.FormattedValue": "18/01/2023",
              "cdhu_clpodtdaalteracaodasituacao": "2023-01-18",
              "cdhu_clpodtdopactoantenupcialatual": null,
              "cdhu_clponmlivroatual": null,
              "cdhu_clponmfolhaatual": null,
              "cdhu_clpodtdataatual": null,
              "cdhu_clponmnomedoconjugeatual": "Teste C\u00F4njuge 123",
              "cdhu_clponmemailconjugeatual": "bozoteste@testebozo.com.br",
              "cdhu_clponmrgdoconjugeatual": "906987412",
              "cdhu_clponmcpfdoconjugeatual": "998.085.520-72",
              "cdhu_clpocoufdorgdoconjugeatual@OData.Community.Display.V1.FormattedValue": "AP",
              "cdhu_clpocoufdorgdoconjugeatual": 808620002,
              "cdhu_clpodhdatadenascimentodoconjugeatual@OData.Community.Display.V1.FormattedValue": "10/12/1979",
              "cdhu_clpodhdatadenascimentodoconjugeatual": "1979-12-10",
              "cdhu_clponmnacionalidadedoconjugeatual": "BRASILEIRA",
              "cdhu_clpocoprofissaodoconjugeatual@OData.Community.Display.V1.FormattedValue": "INDUSTRIARIO",
              "cdhu_clpocoprofissaodoconjugeatual": 100000000,
              "cdhu_clponmnomedamaedoconjugeatual": "Narigas",
              "cdhu_coreracadoconjugeatual@OData.Community.Display.V1.FormattedValue": "Preta",
              "cdhu_coreracadoconjugeatual": 2,
              "bp_clpoplestadocivildoconjuge@OData.Community.Display.V1.FormattedValue": "Casado",
              "bp_clpoplestadocivildoconjuge": 1,
              "cdhu_clpocograudeinstrucao@OData.Community.Display.V1.FormattedValue": "7 - 7\u00AA s\u00E9rie do fundamental (antiga 6\u00AA s\u00E9rie)",
              "cdhu_clpocograudeinstrucao": 7,
              "bp_clpoplgraudeinstrucaoconj@OData.Community.Display.V1.FormattedValue": "2 - 2\u00AA s\u00E9rie do fundamental (antiga 1\u00AA s\u00E9rie)",
              "bp_clpoplgraudeinstrucaoconj": 2,
              "bp_clpostnomedocompanheirodoconjuge": null,
              "cdhu_clponmnomesocialapelido": null,
              "bp_clpobtconfirmacaoveracidadedasinformacoes@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clpobtconfirmacaoveracidadedasinformacoes": false,
              "cdhu_clpocoprofissaocbo@OData.Community.Display.V1.FormattedValue": "INDUSTRIARIO",
              "cdhu_clpocoprofissaocbo": 100000000,
              "bp_clpoitquantaspessoastemrenda": null,
              "bp_clpobtseunucleofamiliarmulheraresponsavel@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clpobtseunucleofamiliarmulheraresponsavel": false,
              "bp_clpomnsesimqualovalormensaldoaluguel": null,
              "bp_clpobtalguemdonucleofamiliarpossuideficie@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clpobtalguemdonucleofamiliarpossuideficie": false,
              "bp_clpobtodeficientevoceseucnjugecompanheiro": null,
              "bp_clpobtmudancadeconjoucompaposauxilio@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clpobtmudancadeconjoucompaposauxilio": false,
              "bp_clpopltipodedeficiencia": null,
              "bp_clpobtvoceecadeirante": null,
              "bp_clpobtnecessidadedeuhadaptada": null,
              "cdhu_clpocosistemaorigem@OData.Community.Display.V1.FormattedValue": "Aux\u00EDlio-Moradia",
              "cdhu_clpocosistemaorigem": 808620000,
              "bp_clpo_pl_sexodoconjugeatual@OData.Community.Display.V1.FormattedValue": "MASCULINO",
              "bp_clpo_pl_sexodoconjugeatual": 2,
              "bp_clpo_mn_rendadoconjugeatual@OData.Community.Display.V1.FormattedValue": "R$ 2.000,00",
              "bp_clpo_mn_rendadoconjugeatual": 2000.0000000000,
              "cdhu_clpovlvalorrendaatual@OData.Community.Display.V1.FormattedValue": "R$ 1.500,00",
              "cdhu_clpovlvalorrendaatual": 1500.0000,
              "bp_cdhu_clponmufdenascimentoconjuge": "BA",
              "_cdhu_idunidadehabitacionalid_value": null,
              "_bp_empreendimentoinscricaoleadid_value": null,
              "cdhu_data_inicio_auxilio_moradia@OData.Community.Display.V1.FormattedValue": "01/02/2023",
              "cdhu_data_inicio_auxilio_moradia": "2023-02-01T03:00:00Z",
              "bp_clpovloutrarendafamiliar@OData.Community.Display.V1.FormattedValue": "R$ 3.500,00",
              "bp_clpovloutrarendafamiliar": 3500.0000000000,
              "_bp_clp_lk_conjugeatual_value@OData.Community.Display.V1.FormattedValue": "Teste C\u00F4njuge 123",
              "_bp_clp_lk_conjugeatual_value": "d630ee34-58a9-41a4-b4ae-d28491d54f0f",
              "_bp_clp_lk_companheiroatual_value@OData.Community.Display.V1.FormattedValue": "Teste Companheiro 321",
              "_bp_clp_lk_companheiroatual_value": "982af2a0-f039-4595-b766-d7c9d90993b0",
              "bp_clp_bt_uniaoestavelatual@OData.Community.Display.V1.FormattedValue": "Sim",
              "bp_clp_bt_uniaoestavelatual": true,
              "bp_clp_bt_confirmacaouniaoestavelatual@OData.Community.Display.V1.FormattedValue": "Sim",
              "bp_clp_bt_confirmacaouniaoestavelatual": true,
              "statecode@OData.Community.Display.V1.FormattedValue": "Aberta",
              "statecode": 0,
              "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "Real",
              "_transactioncurrencyid_value": "c09c1735-b749-e611-80e6-2c59e53a159c",
              "address1_composite": "Jos\u00E9 Mascarenhas, 10\r\nVila Matilde\r\nSAO PAULO - SP\r\nBRASIL\r\n03515-000",
              "cdhu_lead_contact": [],
              "cdhu_lead_contact@odata.nextLink": "https://cdhucrmdev.api.crm2.dynamics.com/api/data/v9.0/leads(a9a43561-f8ff-ed11-8f6d-002248e05a89)/cdhu_lead_contact?$select=contactid"
            },
            {
              "@odata.etag": "W/\u00227089617145\u0022",
              "leadid": "2c3d8fd8-c214-416f-afb2-e700b86c9c16",
              "cdhu_clponmcpf": "913.968.597-72",
              "cdhu_clpococpfconfirmadopordocumento": null,
              "firstname": "AARAO LUIZ DA SILVA",
              "cdhu_projeto_origem": "Projeto Taubat\u00E9",
              "cdhu_tipodeatendimento@OData.Community.Display.V1.FormattedValue": "Atualiza\u00E7\u00E3o Anual",
              "cdhu_tipodeatendimento": 808620000,
              "cdhu_clponmrg": " 22.425.641-5",
              "cdhu_clpocorgernourgrne@OData.Community.Display.V1.FormattedValue": "1 - RG",
              "cdhu_clpocorgernourgrne": 1,
              "cdhu_clpocoufrg@OData.Community.Display.V1.FormattedValue": "SP",
              "cdhu_clpocoufrg": 808620024,
              "cdhu_clpocosexo@OData.Community.Display.V1.FormattedValue": "MASCULINO",
              "cdhu_clpocosexo": 2,
              "cdhu_clponmnomedamae": " ANDREIA ROCHA",
              "cdhu_clpodhdatadenascimento@OData.Community.Display.V1.FormattedValue": "07/10/1966",
              "cdhu_clpodhdatadenascimento": "1966-10-07",
              "cdhu_clponuidade@OData.Community.Display.V1.FormattedValue": "56",
              "cdhu_clponuidade": 56,
              "cdhu_clponmcidadedenascimento": "SAO PAULO",
              "cdhu_clponmufdenascimento": "SP",
              "cdhu_clponmnacionalidade": "BRASILEIRA",
              "cdhu_clponmcoreraca@OData.Community.Display.V1.FormattedValue": "Preta",
              "cdhu_clponmcoreraca": 2,
              "address1_line1": "Jos\u00E9 Mascarenhas, 10",
              "address1_line2": null,
              "address1_line3": "Vila Matilde",
              "address1_city": "SAO PAULO",
              "address1_stateorprovince": "SP",
              "address1_country": "BRASIL",
              "address1_addresstypecode@OData.Community.Display.V1.FormattedValue": "\u00C1rea Urbana",
              "address1_addresstypecode": 1,
              "address1_postalcode": "03515-000",
              "_bp_clpo_lk_1opcaomunicipio_value": null,
              "_bp_clpo_lk_2opcaomunicipio_value": null,
              "_bp_clpo_lk_3opcaomunicipio_value": null,
              "bp_clpo_co_1opcaozona": null,
              "bp_clpo_co_2opcaozona": null,
              "bp_clpo_co_3opcaozona": null,
              "cdhu_clpocologradouro@OData.Community.Display.V1.FormattedValue": "RUA",
              "cdhu_clpocologradouro": 7,
              "bp_clpopltipodemoradia@OData.Community.Display.V1.FormattedValue": "Cedida",
              "bp_clpopltipodemoradia": 2,
              "bp_clpoittempomoradiaestadosp@OData.Community.Display.V1.FormattedValue": "10",
              "bp_clpoittempomoradiaestadosp": 10,
              "bp_clpoittempodemoradiamunicipiosp@OData.Community.Display.V1.FormattedValue": "10",
              "bp_clpoittempodemoradiamunicipiosp": 10,
              "emailaddress1": null,
              "mobilephone": null,
              "cdhu_clpocomesmoestadocivil@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "cdhu_clpocomesmoestadocivil": false,
              "cdhu_clpocoestadocivilatual@OData.Community.Display.V1.FormattedValue": "Solteiro",
              "cdhu_clpocoestadocivilatual": 6,
              "cdhu_clpodtcasamentoatual": null,
              "cdhu_clpocoregimedebensatual@OData.Community.Display.V1.FormattedValue": "N\u00E3o se aplica",
              "cdhu_clpocoregimedebensatual": 0,
              "cdhu_clpocosituacao@OData.Community.Display.V1.FormattedValue": "Ativo",
              "cdhu_clpocosituacao": 1,
              "cdhu_clponmnib": "878711",
              "cdhu_clpodtdaalteracaodasituacao@OData.Community.Display.V1.FormattedValue": "08/02/2023",
              "cdhu_clpodtdaalteracaodasituacao": "2023-02-08",
              "cdhu_clpodtdopactoantenupcialatual": null,
              "cdhu_clponmlivroatual": null,
              "cdhu_clponmfolhaatual": null,
              "cdhu_clpodtdataatual": null,
              "cdhu_clponmnomedoconjugeatual": null,
              "cdhu_clponmemailconjugeatual": null,
              "cdhu_clponmrgdoconjugeatual": null,
              "cdhu_clponmcpfdoconjugeatual": null,
              "cdhu_clpocoufdorgdoconjugeatual": null,
              "cdhu_clpodhdatadenascimentodoconjugeatual": null,
              "cdhu_clponmnacionalidadedoconjugeatual": null,
              "cdhu_clpocoprofissaodoconjugeatual": null,
              "cdhu_clponmnomedamaedoconjugeatual": null,
              "cdhu_coreracadoconjugeatual": null,
              "bp_clpoplestadocivildoconjuge": null,
              "cdhu_clpocograudeinstrucao@OData.Community.Display.V1.FormattedValue": "7 - 7\u00AA s\u00E9rie do fundamental (antiga 6\u00AA s\u00E9rie)",
              "cdhu_clpocograudeinstrucao": 7,
              "bp_clpoplgraudeinstrucaoconj": null,
              "bp_clpostnomedocompanheirodoconjuge": null,
              "cdhu_clponmnomesocialapelido": null,
              "bp_clpobtconfirmacaoveracidadedasinformacoes": null,
              "cdhu_clpocoprofissaocbo@OData.Community.Display.V1.FormattedValue": "INDUSTRIARIO",
              "cdhu_clpocoprofissaocbo": 100000000,
              "bp_clpoitquantaspessoastemrenda": null,
              "bp_clpobtseunucleofamiliarmulheraresponsavel@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clpobtseunucleofamiliarmulheraresponsavel": false,
              "bp_clpomnsesimqualovalormensaldoaluguel": null,
              "bp_clpobtalguemdonucleofamiliarpossuideficie@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clpobtalguemdonucleofamiliarpossuideficie": false,
              "bp_clpobtodeficientevoceseucnjugecompanheiro": null,
              "bp_clpobtmudancadeconjoucompaposauxilio@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clpobtmudancadeconjoucompaposauxilio": false,
              "bp_clpopltipodedeficiencia": null,
              "bp_clpobtvoceecadeirante": null,
              "bp_clpobtnecessidadedeuhadaptada": null,
              "cdhu_clpocosistemaorigem@OData.Community.Display.V1.FormattedValue": "Gest\u00E3o de Carteira",
              "cdhu_clpocosistemaorigem": 5,
              "bp_clpo_pl_sexodoconjugeatual": null,
              "bp_clpo_mn_rendadoconjugeatual": null,
              "cdhu_clpovlvalorrendaatual@OData.Community.Display.V1.FormattedValue": "R$ 1.500,00",
              "cdhu_clpovlvalorrendaatual": 1500.0000,
              "bp_cdhu_clponmufdenascimentoconjuge": null,
              "_cdhu_idunidadehabitacionalid_value@OData.Community.Display.V1.FormattedValue": "3282183",
              "_cdhu_idunidadehabitacionalid_value": "1b392563-6e19-4aa5-9ad5-b692b6a190e5",
              "_bp_empreendimentoinscricaoleadid_value": null,
              "cdhu_data_inicio_auxilio_moradia@OData.Community.Display.V1.FormattedValue": "04/05/2023",
              "cdhu_data_inicio_auxilio_moradia": "2023-05-04T03:00:00Z",
              "bp_clpovloutrarendafamiliar@OData.Community.Display.V1.FormattedValue": "R$ 1.723,22",
              "bp_clpovloutrarendafamiliar": 1723.2200000000,
              "_bp_clp_lk_conjugeatual_value": null,
              "_bp_clp_lk_companheiroatual_value": null,
              "bp_clp_bt_uniaoestavelatual@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clp_bt_uniaoestavelatual": false,
              "bp_clp_bt_confirmacaouniaoestavelatual@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clp_bt_confirmacaouniaoestavelatual": false,
              "statecode@OData.Community.Display.V1.FormattedValue": "Aberta",
              "statecode": 0,
              "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "Real",
              "_transactioncurrencyid_value": "c09c1735-b749-e611-80e6-2c59e53a159c",
              "address1_composite": "Jos\u00E9 Mascarenhas, 10\r\nVila Matilde\r\nSAO PAULO - SP\r\nBRASIL\r\n03515-000",
              "cdhu_lead_contact": [
                {
                  "@odata.etag": "W/\u00227088984986\u0022",
                  "contactid": "767c84cf-ec54-4db9-8784-6929027914cb",
                  "_cdhu_idclientepotencialcdhuid_value@OData.Community.Display.V1.FormattedValue": "AARAO LUIZ DA SILVA",
                  "_cdhu_idclientepotencialcdhuid_value": "2c3d8fd8-c214-416f-afb2-e700b86c9c16"
                }
              ],
              "cdhu_lead_contact@odata.nextLink": "https://cdhucrmdev.api.crm2.dynamics.com/api/data/v9.0/leads(2c3d8fd8-c214-416f-afb2-e700b86c9c16)/cdhu_lead_contact?$select=contactid"
            }
          ]
        }
        """;

    private const string _jsonSubject2 = """
        {
          "@odata.context": "https://cdhucrmdev.api.crm2.dynamics.com/api/data/v9.0/$metadatabp_questionarios(bp_questionarioid,bp_quest_st_cep,bp_quest_st_bairro,bp_quest_bt_mudanca_conjuge_auxilio,bp_quest_pl_tipo_logradouro,bp_quest_st_nomelogradouro,bp_quest_it_nresidencia,bp_quest_st_complemento,bp_quest_st_pais,bp_quest_pl_tipo_questionario,bp_quest_st_celular,bp_quest_pl_estado,bp_quest_st_whatsapp,bp_quest_st_outro_celular_contato,bp_quest_st_nome_contato_recado,bp_quest_st_email,bp_quest_pl_tipo_moradia,bp_quest_st_cel_recado,bp_quest_it_tempo_moradia_estado_sp,bp_quest_it_tempo_moradia_municipio_sp,bp_quest_pl_profissao,bp_quest_mn_renda_atual,bp_quest_st_nome_completo_titular,bp_quest_st_cpf,bp_quest_pl_cpf_confirmado,bp_quest_pl_rg_rne,bp_quest_st_numero_identidade,bp_quest_pl_uf_rg,bp_quest_pl_sexo,bp_quest_st_nome_mae,bp_quest_dt_nascimento,bp_quest_st_municipio_nascimento,bp_quest_pl_grau_escolaridade,bp_quest_pl_uf_nascimento,bp_quest_st_nacionalidade,bp_quest_pl_raca_cor,bp_quest_pl_localizacao_moradia,bp_quest_pl_estado_civil,bp_quest_pl_regime_bens,bp_quest_dt_casamento_atual,bp_quest_dt_pacto_antenupcial,bp_quest_st_livro,bp_quest_st_folha,bp_quest_dt_data,bp_quest_st_nome_conjuge,bp_quest_st_email_conjuge,bp_quest_st_cpf_conjuge,bp_quest_rg_conjuge,bp_quest_pl_uf_rg_conjuge,bp_quest_pl_sexo_conjuge,bp_quest_dt_data_nascimento_conjuge,bp_quest_pl_uf_nascimento_conjuge,bp_quest_st_nacionalidade_conjuge,bp_quest_st_nome_mae_conjuge,bp_quest_pl_raca_cor_conjuge,bp_quest_pl_grau_escolaridade_conjuge,bp_quest_pl_estado_civil_conjuge,bp_quest_pl_profissao_conjuge,bp_quest_mn_renda_conjuge,bp_quest_bt_nucleo_familiar_mulher_respons,bp_quest_bt_voce_paga_aluguel_imovel,bp_quest_mn_valor_mensal_aluguel,bp_quest_bt_nucleo_familiar_deficiencia,bp_quest_pl_qual_tipo_deficiencia,bp_quest_bt_pessoa_deficiencia_voce,bp_quest_bt_voce_cadeirante,bp_quest_bt_unidade_habitacional_adaptada,bp_quest_pl_zonapara1municipio,bp_quest_pl_zonapara2municipio,bp_quest_pl_zonapara3municipio,bp_quest_pl_situacaodoauxilio,bp_quest_st_nib,bp_quest_dt_alteracaodasituacao,bp_quest_st_projetodeorigem,bp_quest_dt_inicioauxiliomoradia,bp_quest_mn_renda_familiar,bp_quest_bt_vive_uniao_estavel,bp_quest_bt_ultimo_quest_respondido,bp_quest_st_nome_companheiro,bp_quest_st_cpf_companheiro,bp_quest_st_email_companheiro,bp_quest_st_rg_companheiro,bp_quest_pl_uf_rg_companheiro,bp_quest_pl_sexo_companheiro,bp_quest_dt_data_nascimento_companheiro,bp_quest_pl_uf_nascimento_companheiro,bp_quest_st_nacionalidade_companheiro,bp_quest_st_nome_mae_companheiro,bp_quest_pl_grau_escolaridade_companheiro,bp_quest_pl_estado_civil_companheiro,bp_quest_pl_raca_cor_companheiro,bp_quest_pl_profissao_companheiro,bp_quest_mn_renda_companheiro,bp_quest_bt_confirma_casado_vive_pessoa,bp_quest_st_conjuge_nome_companheiro,bp_quest_st_conjuge_cpf_companheiro,bp_quest_st_conjuge_email_companheiro,bp_quest_st_rg_conjuge_companheiro,bp_quest_pl_uf_rg_conjuge_companheiro,bp_quest_pl_sexo_conjuge_companheiro,bp_quest_dt_nascimento_conjuge_companheiro,bp_quest_pl_uf_nascimento_conjuge_comp,bp_quest_st_nacionalidade_conjuge_comp,bp_quest_st_nome_mae_conjuge_companheiro,bp_quest_pl_cor_raca_conjuge_companheiro,bp_quest_pl_grau_escolaridade_conjuge_comp,bp_quest_pl_estado_civil_conjuge_companheiro,bp_quest_pl_profissao_conjuge_companheiro,bp_quest_mn_renda_conjuge_companheiro,bp_quest_st_nome_social_conjuge,bp_quest_st_nome_social_companheiro,bp_quest_st_nome_social_conjuge_companheiro,_bp_quest_lk_cidade_value,_bp_questionarioleadid_value,_bp_quest_lk_1opcaodemunicipio_value,_bp_quest_lk_2opcaodemunicipio_value,_bp_quest_lk_3opcaodemunicipio_value,_bp_quest_lk_habilitacaoquestionario_value)",
          "value": [
            {
              "@odata.etag": "W/\u00227089632689\u0022",
              "bp_questionarioid": "e3d64940-0a76-4647-ae4a-9b9d52539527",
              "bp_quest_st_cep": "03515-000",
              "bp_quest_st_bairro": "Vila Matilde",
              "bp_quest_bt_mudanca_conjuge_auxilio@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_quest_bt_mudanca_conjuge_auxilio": false,
              "bp_quest_pl_tipo_logradouro@OData.Community.Display.V1.FormattedValue": "RUA",
              "bp_quest_pl_tipo_logradouro": 7,
              "bp_quest_st_nomelogradouro": "Jos\u00E9 Mascarenhas",
              "bp_quest_it_nresidencia@OData.Community.Display.V1.FormattedValue": "10",
              "bp_quest_it_nresidencia": 10,
              "bp_quest_st_complemento": null,
              "bp_quest_st_pais": "BRASIL",
              "bp_quest_pl_tipo_questionario@OData.Community.Display.V1.FormattedValue": "Auxilio Moradia",
              "bp_quest_pl_tipo_questionario": 2,
              "bp_quest_st_celular": "(83) 98688-4442",
              "bp_quest_pl_estado@OData.Community.Display.V1.FormattedValue": "SP",
              "bp_quest_pl_estado": 808620024,
              "bp_quest_st_whatsapp": "(83) 98688-4442",
              "bp_quest_st_outro_celular_contato": null,
              "bp_quest_st_nome_contato_recado": null,
              "bp_quest_st_email": "AURORALUANAROCHA@LOCARE-EVENTOS.COM.BR",
              "bp_quest_pl_tipo_moradia@OData.Community.Display.V1.FormattedValue": "Cedida",
              "bp_quest_pl_tipo_moradia": 2,
              "bp_quest_st_cel_recado": null,
              "bp_quest_it_tempo_moradia_estado_sp@OData.Community.Display.V1.FormattedValue": "10",
              "bp_quest_it_tempo_moradia_estado_sp": 10,
              "bp_quest_it_tempo_moradia_municipio_sp@OData.Community.Display.V1.FormattedValue": "10",
              "bp_quest_it_tempo_moradia_municipio_sp": 10,
              "bp_quest_pl_profissao@OData.Community.Display.V1.FormattedValue": "INDUSTRIARIO",
              "bp_quest_pl_profissao": 100000000,
              "bp_quest_mn_renda_atual@OData.Community.Display.V1.FormattedValue": "R$ 1.500,00",
              "bp_quest_mn_renda_atual": 1500.0000000000,
              "bp_quest_st_nome_completo_titular": "AARAO LUIZ DA SILVA",
              "bp_quest_st_cpf": "913.968.597-72",
              "bp_quest_pl_cpf_confirmado": null,
              "bp_quest_pl_rg_rne@OData.Community.Display.V1.FormattedValue": "1 - RG",
              "bp_quest_pl_rg_rne": 1,
              "bp_quest_st_numero_identidade": " 22.425.641-5",
              "bp_quest_pl_uf_rg@OData.Community.Display.V1.FormattedValue": "SP",
              "bp_quest_pl_uf_rg": 808620024,
              "bp_quest_pl_sexo@OData.Community.Display.V1.FormattedValue": "MASCULINO",
              "bp_quest_pl_sexo": 2,
              "bp_quest_st_nome_mae": " ANDREIA ROCHA",
              "bp_quest_dt_nascimento@OData.Community.Display.V1.FormattedValue": "07/10/1966",
              "bp_quest_dt_nascimento": "1966-10-07",
              "bp_quest_st_municipio_nascimento": "SAO PAULO",
              "bp_quest_pl_grau_escolaridade@OData.Community.Display.V1.FormattedValue": "7 - 7\u00AA s\u00E9rie do fundamental (antiga 6\u00AA s\u00E9rie)",
              "bp_quest_pl_grau_escolaridade": 7,
              "bp_quest_pl_uf_nascimento@OData.Community.Display.V1.FormattedValue": "SP",
              "bp_quest_pl_uf_nascimento": 808620024,
              "bp_quest_st_nacionalidade": "BRASILEIRA",
              "bp_quest_pl_raca_cor@OData.Community.Display.V1.FormattedValue": "Preta",
              "bp_quest_pl_raca_cor": 2,
              "bp_quest_pl_localizacao_moradia@OData.Community.Display.V1.FormattedValue": "\u00C1rea Urbana",
              "bp_quest_pl_localizacao_moradia": 1,
              "bp_quest_pl_estado_civil@OData.Community.Display.V1.FormattedValue": "Casado",
              "bp_quest_pl_estado_civil": 1,
              "bp_quest_pl_regime_bens@OData.Community.Display.V1.FormattedValue": "Comunh\u00E3o Parcial de Bens na Vig\u00EAncia \u00E0 Lei do Div\u00F3rcio n\u00B0 6515/1977",
              "bp_quest_pl_regime_bens": 2,
              "bp_quest_dt_casamento_atual@OData.Community.Display.V1.FormattedValue": "05/08/1999",
              "bp_quest_dt_casamento_atual": "1999-08-05",
              "bp_quest_dt_pacto_antenupcial": null,
              "bp_quest_st_livro": null,
              "bp_quest_st_folha": null,
              "bp_quest_dt_data": null,
              "bp_quest_st_nome_conjuge": "Teste C\u00F4njuge 123",
              "bp_quest_st_email_conjuge": "bozoteste@testebozo.com.br",
              "bp_quest_st_cpf_conjuge": "998.085.520-72",
              "bp_quest_rg_conjuge": "906987412",
              "bp_quest_pl_uf_rg_conjuge@OData.Community.Display.V1.FormattedValue": "AP",
              "bp_quest_pl_uf_rg_conjuge": 808620002,
              "bp_quest_pl_sexo_conjuge@OData.Community.Display.V1.FormattedValue": "MASCULINO",
              "bp_quest_pl_sexo_conjuge": 2,
              "bp_quest_dt_data_nascimento_conjuge@OData.Community.Display.V1.FormattedValue": "10/12/1979",
              "bp_quest_dt_data_nascimento_conjuge": "1979-12-10",
              "bp_quest_pl_uf_nascimento_conjuge@OData.Community.Display.V1.FormattedValue": "BA",
              "bp_quest_pl_uf_nascimento_conjuge": 808620004,
              "bp_quest_st_nacionalidade_conjuge": "BRASILEIRA",
              "bp_quest_st_nome_mae_conjuge": "Narigas",
              "bp_quest_pl_raca_cor_conjuge@OData.Community.Display.V1.FormattedValue": "Preta",
              "bp_quest_pl_raca_cor_conjuge": 2,
              "bp_quest_pl_grau_escolaridade_conjuge@OData.Community.Display.V1.FormattedValue": "2 - 2\u00AA s\u00E9rie do fundamental (antiga 1\u00AA s\u00E9rie)",
              "bp_quest_pl_grau_escolaridade_conjuge": 2,
              "bp_quest_pl_estado_civil_conjuge@OData.Community.Display.V1.FormattedValue": "Casado",
              "bp_quest_pl_estado_civil_conjuge": 1,
              "bp_quest_pl_profissao_conjuge@OData.Community.Display.V1.FormattedValue": "INDUSTRIARIO",
              "bp_quest_pl_profissao_conjuge": 100000000,
              "bp_quest_mn_renda_conjuge@OData.Community.Display.V1.FormattedValue": "R$ 2.000,00",
              "bp_quest_mn_renda_conjuge": 2000.0000000000,
              "bp_quest_bt_nucleo_familiar_mulher_respons@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_quest_bt_nucleo_familiar_mulher_respons": false,
              "bp_quest_bt_voce_paga_aluguel_imovel@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_quest_bt_voce_paga_aluguel_imovel": false,
              "bp_quest_mn_valor_mensal_aluguel": null,
              "bp_quest_bt_nucleo_familiar_deficiencia@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_quest_bt_nucleo_familiar_deficiencia": false,
              "bp_quest_pl_qual_tipo_deficiencia": null,
              "bp_quest_bt_pessoa_deficiencia_voce@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_quest_bt_pessoa_deficiencia_voce": false,
              "bp_quest_bt_voce_cadeirante@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_quest_bt_voce_cadeirante": false,
              "bp_quest_bt_unidade_habitacional_adaptada@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_quest_bt_unidade_habitacional_adaptada": false,
              "bp_quest_pl_zonapara1municipio": null,
              "bp_quest_pl_zonapara2municipio": null,
              "bp_quest_pl_zonapara3municipio": null,
              "bp_quest_pl_situacaodoauxilio@OData.Community.Display.V1.FormattedValue": "Ativo",
              "bp_quest_pl_situacaodoauxilio": 1,
              "bp_quest_st_nib": "656565",
              "bp_quest_dt_alteracaodasituacao@OData.Community.Display.V1.FormattedValue": "18/01/2023",
              "bp_quest_dt_alteracaodasituacao": "2023-01-18",
              "bp_quest_st_projetodeorigem": "Projeto Cubat\u00E3o",
              "bp_quest_dt_inicioauxiliomoradia@OData.Community.Display.V1.FormattedValue": "01/02/2023",
              "bp_quest_dt_inicioauxiliomoradia": "2023-02-01",
              "bp_quest_mn_renda_familiar@OData.Community.Display.V1.FormattedValue": "R$ 3.500,00",
              "bp_quest_mn_renda_familiar": 3500.0000000000,
              "bp_quest_bt_vive_uniao_estavel@OData.Community.Display.V1.FormattedValue": "Sim",
              "bp_quest_bt_vive_uniao_estavel": true,
              "bp_quest_bt_ultimo_quest_respondido@OData.Community.Display.V1.FormattedValue": "Sim",
              "bp_quest_bt_ultimo_quest_respondido": true,
              "bp_quest_st_nome_companheiro": "Teste Companheiro 321",
              "bp_quest_st_cpf_companheiro": "707.297.020-73",
              "bp_quest_st_email_companheiro": "nariguda@narigasteste.com.br",
              "bp_quest_st_rg_companheiro": "306987412",
              "bp_quest_pl_uf_rg_companheiro@OData.Community.Display.V1.FormattedValue": "AC",
              "bp_quest_pl_uf_rg_companheiro": 808620000,
              "bp_quest_pl_sexo_companheiro@OData.Community.Display.V1.FormattedValue": "FEMININO",
              "bp_quest_pl_sexo_companheiro": 1,
              "bp_quest_dt_data_nascimento_companheiro@OData.Community.Display.V1.FormattedValue": "11/11/1969",
              "bp_quest_dt_data_nascimento_companheiro": "1969-11-11",
              "bp_quest_pl_uf_nascimento_companheiro@OData.Community.Display.V1.FormattedValue": "AP",
              "bp_quest_pl_uf_nascimento_companheiro": 808620002,
              "bp_quest_st_nacionalidade_companheiro": "BRASILEIRA",
              "bp_quest_st_nome_mae_companheiro": "Narigudass",
              "bp_quest_pl_grau_escolaridade_companheiro@OData.Community.Display.V1.FormattedValue": "2 - 2\u00AA s\u00E9rie do fundamental (antiga 1\u00AA s\u00E9rie)",
              "bp_quest_pl_grau_escolaridade_companheiro": 2,
              "bp_quest_pl_estado_civil_companheiro@OData.Community.Display.V1.FormattedValue": "Casado",
              "bp_quest_pl_estado_civil_companheiro": 1,
              "bp_quest_pl_raca_cor_companheiro@OData.Community.Display.V1.FormattedValue": "Preta",
              "bp_quest_pl_raca_cor_companheiro": 2,
              "bp_quest_pl_profissao_companheiro@OData.Community.Display.V1.FormattedValue": "INDUSTRIARIO",
              "bp_quest_pl_profissao_companheiro": 100000000,
              "bp_quest_mn_renda_companheiro@OData.Community.Display.V1.FormattedValue": "R$ 2.500,00",
              "bp_quest_mn_renda_companheiro": 2500.0000000000,
              "bp_quest_bt_confirma_casado_vive_pessoa@OData.Community.Display.V1.FormattedValue": "Sim",
              "bp_quest_bt_confirma_casado_vive_pessoa": true,
              "bp_quest_st_conjuge_nome_companheiro": "Conjuge do companheiro 321",
              "bp_quest_st_conjuge_cpf_companheiro": "333.333.333-33",
              "bp_quest_st_conjuge_email_companheiro": "Teste@teste",
              "bp_quest_st_rg_conjuge_companheiro": "34343",
              "bp_quest_pl_uf_rg_conjuge_companheiro@OData.Community.Display.V1.FormattedValue": "AP",
              "bp_quest_pl_uf_rg_conjuge_companheiro": 808620002,
              "bp_quest_pl_sexo_conjuge_companheiro@OData.Community.Display.V1.FormattedValue": "FEMININO",
              "bp_quest_pl_sexo_conjuge_companheiro": 1,
              "bp_quest_dt_nascimento_conjuge_companheiro@OData.Community.Display.V1.FormattedValue": "05/05/2000",
              "bp_quest_dt_nascimento_conjuge_companheiro": "2000-05-05",
              "bp_quest_pl_uf_nascimento_conjuge_comp@OData.Community.Display.V1.FormattedValue": "AL",
              "bp_quest_pl_uf_nascimento_conjuge_comp": 808620001,
              "bp_quest_st_nacionalidade_conjuge_comp": "BRASILEIRA",
              "bp_quest_st_nome_mae_conjuge_companheiro": "Teste",
              "bp_quest_pl_cor_raca_conjuge_companheiro@OData.Community.Display.V1.FormattedValue": "Amarela",
              "bp_quest_pl_cor_raca_conjuge_companheiro": 3,
              "bp_quest_pl_grau_escolaridade_conjuge_comp@OData.Community.Display.V1.FormattedValue": "4 - 4\u00AA s\u00E9rie do fundamental (antiga 3\u00AA s\u00E9rie)",
              "bp_quest_pl_grau_escolaridade_conjuge_comp": 4,
              "bp_quest_pl_estado_civil_conjuge_companheiro@OData.Community.Display.V1.FormattedValue": "Desquitado",
              "bp_quest_pl_estado_civil_conjuge_companheiro": 5,
              "bp_quest_pl_profissao_conjuge_companheiro@OData.Community.Display.V1.FormattedValue": "FUNC PUB EST",
              "bp_quest_pl_profissao_conjuge_companheiro": 100000001,
              "bp_quest_mn_renda_conjuge_companheiro@OData.Community.Display.V1.FormattedValue": "R$ 121,00",
              "bp_quest_mn_renda_conjuge_companheiro": 121.0000000000,
              "bp_quest_st_nome_social_conjuge": null,
              "bp_quest_st_nome_social_companheiro": null,
              "bp_quest_st_nome_social_conjuge_companheiro": null,
              "_bp_quest_lk_cidade_value@OData.Community.Display.V1.FormattedValue": "SAO PAULO",
              "_bp_quest_lk_cidade_value": "7364609e-7ded-4c53-8000-b3411c56ff9f",
              "_bp_questionarioleadid_value@OData.Community.Display.V1.FormattedValue": "AARAO LUIZ DA SILVA",
              "_bp_questionarioleadid_value": "a9a43561-f8ff-ed11-8f6d-002248e05a89",
              "_bp_quest_lk_1opcaodemunicipio_value": null,
              "_bp_quest_lk_2opcaodemunicipio_value": null,
              "_bp_quest_lk_3opcaodemunicipio_value": null,
              "_bp_quest_lk_habilitacaoquestionario_value": null,
              "createdon@OData.Community.Display.V1.FormattedValue": "06/06/2023 19:53",
              "createdon": "2023-06-06T19:53:57Z",
              "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "Real",
              "_transactioncurrencyid_value": "c09c1735-b749-e611-80e6-2c59e53a159c"
            }
          ]
        }
        """;
}

