using FluentAssertions;
using System.Text.Json;

namespace Cblx.Blocks.Json.Tests.RealWorld.Case3;

public class Tests
{
    [Theory]
    [InlineData(_jsonSubject)]
    public void Deserializing(string json)
    {
        var clientesPotenciais = JsonSerializer.Deserialize<Result>(json)!;
        clientesPotenciais.Value.Should().SatisfyRespectively(
          c => {
            c.Id.Should().Be("a9a43561-f8ff-ed11-8f6d-002248e05a89");
            c.Cpf.Should().Be("913.968.597-72");
          },
          c => {
            c.Id.Should().Be("2c3d8fd8-c214-416f-afb2-e700b86c9c16");
            c.Cpf.Should().Be("913.968.597-72");
          }
        );
    }

    private const string _jsonSubject = """
        {
          "@odata.context": "https://cdhucrmdev.api.crm2.dynamics.com/api/data/v9.0/$metadataleads(leadid,cdhu_clponmcpf,cdhu_clpococpfconfirmadopordocumento,firstname,cdhu_projeto_origem,cdhu_tipodeatendimento,cdhu_clponmrg,cdhu_clpocorgernourgrne,cdhu_clpocoufrg,cdhu_clpocosexo,cdhu_clponmnomedamae,cdhu_clpodhdatadenascimento,cdhu_clponuidade,cdhu_clponmcidadedenascimento,cdhu_clponmufdenascimento,cdhu_clponmnacionalidade,cdhu_clponmcoreraca,address1_line1,address1_line2,address1_line3,address1_city,address1_stateorprovince,address1_country,address1_addresstypecode,address1_postalcode,_bp_clpo_lk_1opcaomunicipio_value,_bp_clpo_lk_2opcaomunicipio_value,_bp_clpo_lk_3opcaomunicipio_value,bp_clpo_co_1opcaozona,bp_clpo_co_2opcaozona,bp_clpo_co_3opcaozona,cdhu_clpocologradouro,bp_clpopltipodemoradia,bp_clpoittempomoradiaestadosp,bp_clpoittempodemoradiamunicipiosp,emailaddress1,mobilephone,cdhu_clpocomesmoestadocivil,cdhu_clpocoestadocivilatual,cdhu_clpodtcasamentoatual,cdhu_clpocoregimedebensatual,cdhu_clpocosituacao,cdhu_clponmnib,cdhu_clpodtdaalteracaodasituacao,cdhu_clpodtdopactoantenupcialatual,cdhu_clponmlivroatual,cdhu_clponmfolhaatual,cdhu_clpodtdataatual,cdhu_clponmnomedoconjugeatual,cdhu_clponmemailconjugeatual,cdhu_clponmrgdoconjugeatual,cdhu_clponmcpfdoconjugeatual,cdhu_clpocoufdorgdoconjugeatual,cdhu_clpodhdatadenascimentodoconjugeatual,cdhu_clponmnacionalidadedoconjugeatual,cdhu_clpocoprofissaodoconjugeatual,cdhu_clponmnomedamaedoconjugeatual,cdhu_coreracadoconjugeatual,bp_clpoplestadocivildoconjuge,cdhu_clpocograudeinstrucao,bp_clpoplgraudeinstrucaoconj,bp_clpostnomedocompanheirodoconjuge,cdhu_clponmnomesocialapelido,bp_clpobtconfirmacaoveracidadedasinformacoes,cdhu_clpocoprofissaocbo,bp_clpoitquantaspessoastemrenda,bp_clpobtseunucleofamiliarmulheraresponsavel,bp_clpomnsesimqualovalormensaldoaluguel,bp_clpobtalguemdonucleofamiliarpossuideficie,bp_clpobtodeficientevoceseucnjugecompanheiro,bp_clpobtmudancadeconjoucompaposauxilio,bp_clpopltipodedeficiencia,bp_clpobtvoceecadeirante,bp_clpobtnecessidadedeuhadaptada,cdhu_clpocosistemaorigem,bp_clpo_pl_sexodoconjugeatual,bp_clpo_mn_rendadoconjugeatual,cdhu_clpovlvalorrendaatual,bp_cdhu_clponmufdenascimentoconjuge,_cdhu_idunidadehabitacionalid_value,_bp_empreendimentoinscricaoleadid_value,cdhu_data_inicio_auxilio_moradia,bp_clpovloutrarendafamiliar,_bp_clp_lk_conjugeatual_value,_bp_clp_lk_companheiroatual_value,bp_clp_bt_uniaoestavelatual,bp_clp_bt_confirmacaouniaoestavelatual,statecode,cdhu_lead_contact(contactid))",
          "value": [
            {
              "@odata.etag": "W/\u00227089632950\u0022",
              "leadid": "a9a43561-f8ff-ed11-8f6d-002248e05a89",
              "cdhu_clponmcpf": "913.968.597-72",
              "cdhu_clpococpfconfirmadopordocumento": null,
              "firstname": "AARAO LUIZ DA SILVA",
              "cdhu_projeto_origem": "Projeto Cubat\u00E3o",
              "cdhu_tipodeatendimento@OData.Community.Display.V1.FormattedValue": "Atualiza\u00E7\u00E3o Anual",
              "cdhu_tipodeatendimento": 808620000,
              "cdhu_clponmrg": " 22.425.641-5",
              "cdhu_clpocorgernourgrne@OData.Community.Display.V1.FormattedValue": "1 - RG",
              "cdhu_clpocorgernourgrne": 1,
              "cdhu_clpocoufrg@OData.Community.Display.V1.FormattedValue": "SP",
              "cdhu_clpocoufrg": 808620024,
              "cdhu_clpocosexo@OData.Community.Display.V1.FormattedValue": "MASCULINO",
              "cdhu_clpocosexo": 2,
              "cdhu_clponmnomedamae": " ANDREIA ROCHA",
              "cdhu_clpodhdatadenascimento@OData.Community.Display.V1.FormattedValue": "07/10/1966",
              "cdhu_clpodhdatadenascimento": "1966-10-07",
              "cdhu_clponuidade@OData.Community.Display.V1.FormattedValue": "56",
              "cdhu_clponuidade": 56,
              "cdhu_clponmcidadedenascimento": "SAO PAULO",
              "cdhu_clponmufdenascimento": "SP",
              "cdhu_clponmnacionalidade": "BRASILEIRA",
              "cdhu_clponmcoreraca@OData.Community.Display.V1.FormattedValue": "Preta",
              "cdhu_clponmcoreraca": 2,
              "address1_line1": "Jos\u00E9 Mascarenhas, 10",
              "address1_line2": null,
              "address1_line3": "Vila Matilde",
              "address1_city": "SAO PAULO",
              "address1_stateorprovince": "SP",
              "address1_country": "BRASIL",
              "address1_addresstypecode@OData.Community.Display.V1.FormattedValue": "\u00C1rea Urbana",
              "address1_addresstypecode": 1,
              "address1_postalcode": "03515-000",
              "_bp_clpo_lk_1opcaomunicipio_value": null,
              "_bp_clpo_lk_2opcaomunicipio_value": null,
              "_bp_clpo_lk_3opcaomunicipio_value": null,
              "bp_clpo_co_1opcaozona": null,
              "bp_clpo_co_2opcaozona": null,
              "bp_clpo_co_3opcaozona": null,
              "cdhu_clpocologradouro@OData.Community.Display.V1.FormattedValue": "RUA",
              "cdhu_clpocologradouro": 7,
              "bp_clpopltipodemoradia@OData.Community.Display.V1.FormattedValue": "Cedida",
              "bp_clpopltipodemoradia": 2,
              "bp_clpoittempomoradiaestadosp@OData.Community.Display.V1.FormattedValue": "10",
              "bp_clpoittempomoradiaestadosp": 10,
              "bp_clpoittempodemoradiamunicipiosp@OData.Community.Display.V1.FormattedValue": "10",
              "bp_clpoittempodemoradiamunicipiosp": 10,
              "emailaddress1": "testessdsdaasdad@testdadade.com.br",
              "mobilephone": null,
              "cdhu_clpocomesmoestadocivil@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "cdhu_clpocomesmoestadocivil": false,
              "cdhu_clpocoestadocivilatual@OData.Community.Display.V1.FormattedValue": "Casado",
              "cdhu_clpocoestadocivilatual": 1,
              "cdhu_clpodtcasamentoatual@OData.Community.Display.V1.FormattedValue": "05/08/1999",
              "cdhu_clpodtcasamentoatual": "1999-08-05T03:00:00Z",
              "cdhu_clpocoregimedebensatual@OData.Community.Display.V1.FormattedValue": "Comunh\u00E3o Parcial de Bens na Vig\u00EAncia \u00E0 Lei do Div\u00F3rcio n\u00B0 6515/1977",
              "cdhu_clpocoregimedebensatual": 2,
              "cdhu_clpocosituacao@OData.Community.Display.V1.FormattedValue": "Ativo",
              "cdhu_clpocosituacao": 1,
              "cdhu_clponmnib": "656565",
              "cdhu_clpodtdaalteracaodasituacao@OData.Community.Display.V1.FormattedValue": "18/01/2023",
              "cdhu_clpodtdaalteracaodasituacao": "2023-01-18",
              "cdhu_clpodtdopactoantenupcialatual": null,
              "cdhu_clponmlivroatual": null,
              "cdhu_clponmfolhaatual": null,
              "cdhu_clpodtdataatual": null,
              "cdhu_clponmnomedoconjugeatual": "Teste C\u00F4njuge 123",
              "cdhu_clponmemailconjugeatual": "bozoteste@testebozo.com.br",
              "cdhu_clponmrgdoconjugeatual": "906987412",
              "cdhu_clponmcpfdoconjugeatual": "998.085.520-72",
              "cdhu_clpocoufdorgdoconjugeatual@OData.Community.Display.V1.FormattedValue": "AP",
              "cdhu_clpocoufdorgdoconjugeatual": 808620002,
              "cdhu_clpodhdatadenascimentodoconjugeatual@OData.Community.Display.V1.FormattedValue": "10/12/1979",
              "cdhu_clpodhdatadenascimentodoconjugeatual": "1979-12-10",
              "cdhu_clponmnacionalidadedoconjugeatual": "BRASILEIRA",
              "cdhu_clpocoprofissaodoconjugeatual@OData.Community.Display.V1.FormattedValue": "INDUSTRIARIO",
              "cdhu_clpocoprofissaodoconjugeatual": 100000000,
              "cdhu_clponmnomedamaedoconjugeatual": "Narigas",
              "cdhu_coreracadoconjugeatual@OData.Community.Display.V1.FormattedValue": "Preta",
              "cdhu_coreracadoconjugeatual": 2,
              "bp_clpoplestadocivildoconjuge@OData.Community.Display.V1.FormattedValue": "Casado",
              "bp_clpoplestadocivildoconjuge": 1,
              "cdhu_clpocograudeinstrucao@OData.Community.Display.V1.FormattedValue": "7 - 7\u00AA s\u00E9rie do fundamental (antiga 6\u00AA s\u00E9rie)",
              "cdhu_clpocograudeinstrucao": 7,
              "bp_clpoplgraudeinstrucaoconj@OData.Community.Display.V1.FormattedValue": "2 - 2\u00AA s\u00E9rie do fundamental (antiga 1\u00AA s\u00E9rie)",
              "bp_clpoplgraudeinstrucaoconj": 2,
              "bp_clpostnomedocompanheirodoconjuge": null,
              "cdhu_clponmnomesocialapelido": null,
              "bp_clpobtconfirmacaoveracidadedasinformacoes@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clpobtconfirmacaoveracidadedasinformacoes": false,
              "cdhu_clpocoprofissaocbo@OData.Community.Display.V1.FormattedValue": "INDUSTRIARIO",
              "cdhu_clpocoprofissaocbo": 100000000,
              "bp_clpoitquantaspessoastemrenda": null,
              "bp_clpobtseunucleofamiliarmulheraresponsavel@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clpobtseunucleofamiliarmulheraresponsavel": false,
              "bp_clpomnsesimqualovalormensaldoaluguel": null,
              "bp_clpobtalguemdonucleofamiliarpossuideficie@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clpobtalguemdonucleofamiliarpossuideficie": false,
              "bp_clpobtodeficientevoceseucnjugecompanheiro": null,
              "bp_clpobtmudancadeconjoucompaposauxilio@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clpobtmudancadeconjoucompaposauxilio": false,
              "bp_clpopltipodedeficiencia": null,
              "bp_clpobtvoceecadeirante": null,
              "bp_clpobtnecessidadedeuhadaptada": null,
              "cdhu_clpocosistemaorigem@OData.Community.Display.V1.FormattedValue": "Aux\u00EDlio-Moradia",
              "cdhu_clpocosistemaorigem": 808620000,
              "bp_clpo_pl_sexodoconjugeatual@OData.Community.Display.V1.FormattedValue": "MASCULINO",
              "bp_clpo_pl_sexodoconjugeatual": 2,
              "bp_clpo_mn_rendadoconjugeatual@OData.Community.Display.V1.FormattedValue": "R$ 2.000,00",
              "bp_clpo_mn_rendadoconjugeatual": 2000.0000000000,
              "cdhu_clpovlvalorrendaatual@OData.Community.Display.V1.FormattedValue": "R$ 1.500,00",
              "cdhu_clpovlvalorrendaatual": 1500.0000,
              "bp_cdhu_clponmufdenascimentoconjuge": "BA",
              "_cdhu_idunidadehabitacionalid_value": null,
              "_bp_empreendimentoinscricaoleadid_value": null,
              "cdhu_data_inicio_auxilio_moradia@OData.Community.Display.V1.FormattedValue": "01/02/2023",
              "cdhu_data_inicio_auxilio_moradia": "2023-02-01T03:00:00Z",
              "bp_clpovloutrarendafamiliar@OData.Community.Display.V1.FormattedValue": "R$ 3.500,00",
              "bp_clpovloutrarendafamiliar": 3500.0000000000,
              "_bp_clp_lk_conjugeatual_value@OData.Community.Display.V1.FormattedValue": "Teste C\u00F4njuge 123",
              "_bp_clp_lk_conjugeatual_value": "d630ee34-58a9-41a4-b4ae-d28491d54f0f",
              "_bp_clp_lk_companheiroatual_value@OData.Community.Display.V1.FormattedValue": "Teste Companheiro 321",
              "_bp_clp_lk_companheiroatual_value": "982af2a0-f039-4595-b766-d7c9d90993b0",
              "bp_clp_bt_uniaoestavelatual@OData.Community.Display.V1.FormattedValue": "Sim",
              "bp_clp_bt_uniaoestavelatual": true,
              "bp_clp_bt_confirmacaouniaoestavelatual@OData.Community.Display.V1.FormattedValue": "Sim",
              "bp_clp_bt_confirmacaouniaoestavelatual": true,
              "statecode@OData.Community.Display.V1.FormattedValue": "Aberta",
              "statecode": 0,
              "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "Real",
              "_transactioncurrencyid_value": "c09c1735-b749-e611-80e6-2c59e53a159c",
              "address1_composite": "Jos\u00E9 Mascarenhas, 10\r\nVila Matilde\r\nSAO PAULO - SP\r\nBRASIL\r\n03515-000",
              "cdhu_lead_contact": [],
              "cdhu_lead_contact@odata.nextLink": "https://cdhucrmdev.api.crm2.dynamics.com/api/data/v9.0/leads(a9a43561-f8ff-ed11-8f6d-002248e05a89)/cdhu_lead_contact?$select=contactid"
            },
            {
              "@odata.etag": "W/\u00227089617145\u0022",
              "leadid": "2c3d8fd8-c214-416f-afb2-e700b86c9c16",
              "cdhu_clponmcpf": "913.968.597-72",
              "cdhu_clpococpfconfirmadopordocumento": null,
              "firstname": "AARAO LUIZ DA SILVA",
              "cdhu_projeto_origem": "Projeto Taubat\u00E9",
              "cdhu_tipodeatendimento@OData.Community.Display.V1.FormattedValue": "Atualiza\u00E7\u00E3o Anual",
              "cdhu_tipodeatendimento": 808620000,
              "cdhu_clponmrg": " 22.425.641-5",
              "cdhu_clpocorgernourgrne@OData.Community.Display.V1.FormattedValue": "1 - RG",
              "cdhu_clpocorgernourgrne": 1,
              "cdhu_clpocoufrg@OData.Community.Display.V1.FormattedValue": "SP",
              "cdhu_clpocoufrg": 808620024,
              "cdhu_clpocosexo@OData.Community.Display.V1.FormattedValue": "MASCULINO",
              "cdhu_clpocosexo": 2,
              "cdhu_clponmnomedamae": " ANDREIA ROCHA",
              "cdhu_clpodhdatadenascimento@OData.Community.Display.V1.FormattedValue": "07/10/1966",
              "cdhu_clpodhdatadenascimento": "1966-10-07",
              "cdhu_clponuidade@OData.Community.Display.V1.FormattedValue": "56",
              "cdhu_clponuidade": 56,
              "cdhu_clponmcidadedenascimento": "SAO PAULO",
              "cdhu_clponmufdenascimento": "SP",
              "cdhu_clponmnacionalidade": "BRASILEIRA",
              "cdhu_clponmcoreraca@OData.Community.Display.V1.FormattedValue": "Preta",
              "cdhu_clponmcoreraca": 2,
              "address1_line1": "Jos\u00E9 Mascarenhas, 10",
              "address1_line2": null,
              "address1_line3": "Vila Matilde",
              "address1_city": "SAO PAULO",
              "address1_stateorprovince": "SP",
              "address1_country": "BRASIL",
              "address1_addresstypecode@OData.Community.Display.V1.FormattedValue": "\u00C1rea Urbana",
              "address1_addresstypecode": 1,
              "address1_postalcode": "03515-000",
              "_bp_clpo_lk_1opcaomunicipio_value": null,
              "_bp_clpo_lk_2opcaomunicipio_value": null,
              "_bp_clpo_lk_3opcaomunicipio_value": null,
              "bp_clpo_co_1opcaozona": null,
              "bp_clpo_co_2opcaozona": null,
              "bp_clpo_co_3opcaozona": null,
              "cdhu_clpocologradouro@OData.Community.Display.V1.FormattedValue": "RUA",
              "cdhu_clpocologradouro": 7,
              "bp_clpopltipodemoradia@OData.Community.Display.V1.FormattedValue": "Cedida",
              "bp_clpopltipodemoradia": 2,
              "bp_clpoittempomoradiaestadosp@OData.Community.Display.V1.FormattedValue": "10",
              "bp_clpoittempomoradiaestadosp": 10,
              "bp_clpoittempodemoradiamunicipiosp@OData.Community.Display.V1.FormattedValue": "10",
              "bp_clpoittempodemoradiamunicipiosp": 10,
              "emailaddress1": null,
              "mobilephone": null,
              "cdhu_clpocomesmoestadocivil@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "cdhu_clpocomesmoestadocivil": false,
              "cdhu_clpocoestadocivilatual@OData.Community.Display.V1.FormattedValue": "Solteiro",
              "cdhu_clpocoestadocivilatual": 6,
              "cdhu_clpodtcasamentoatual": null,
              "cdhu_clpocoregimedebensatual@OData.Community.Display.V1.FormattedValue": "N\u00E3o se aplica",
              "cdhu_clpocoregimedebensatual": 0,
              "cdhu_clpocosituacao@OData.Community.Display.V1.FormattedValue": "Ativo",
              "cdhu_clpocosituacao": 1,
              "cdhu_clponmnib": "878711",
              "cdhu_clpodtdaalteracaodasituacao@OData.Community.Display.V1.FormattedValue": "08/02/2023",
              "cdhu_clpodtdaalteracaodasituacao": "2023-02-08",
              "cdhu_clpodtdopactoantenupcialatual": null,
              "cdhu_clponmlivroatual": null,
              "cdhu_clponmfolhaatual": null,
              "cdhu_clpodtdataatual": null,
              "cdhu_clponmnomedoconjugeatual": null,
              "cdhu_clponmemailconjugeatual": null,
              "cdhu_clponmrgdoconjugeatual": null,
              "cdhu_clponmcpfdoconjugeatual": null,
              "cdhu_clpocoufdorgdoconjugeatual": null,
              "cdhu_clpodhdatadenascimentodoconjugeatual": null,
              "cdhu_clponmnacionalidadedoconjugeatual": null,
              "cdhu_clpocoprofissaodoconjugeatual": null,
              "cdhu_clponmnomedamaedoconjugeatual": null,
              "cdhu_coreracadoconjugeatual": null,
              "bp_clpoplestadocivildoconjuge": null,
              "cdhu_clpocograudeinstrucao@OData.Community.Display.V1.FormattedValue": "7 - 7\u00AA s\u00E9rie do fundamental (antiga 6\u00AA s\u00E9rie)",
              "cdhu_clpocograudeinstrucao": 7,
              "bp_clpoplgraudeinstrucaoconj": null,
              "bp_clpostnomedocompanheirodoconjuge": null,
              "cdhu_clponmnomesocialapelido": null,
              "bp_clpobtconfirmacaoveracidadedasinformacoes": null,
              "cdhu_clpocoprofissaocbo@OData.Community.Display.V1.FormattedValue": "INDUSTRIARIO",
              "cdhu_clpocoprofissaocbo": 100000000,
              "bp_clpoitquantaspessoastemrenda": null,
              "bp_clpobtseunucleofamiliarmulheraresponsavel@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clpobtseunucleofamiliarmulheraresponsavel": false,
              "bp_clpomnsesimqualovalormensaldoaluguel": null,
              "bp_clpobtalguemdonucleofamiliarpossuideficie@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clpobtalguemdonucleofamiliarpossuideficie": false,
              "bp_clpobtodeficientevoceseucnjugecompanheiro": null,
              "bp_clpobtmudancadeconjoucompaposauxilio@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clpobtmudancadeconjoucompaposauxilio": false,
              "bp_clpopltipodedeficiencia": null,
              "bp_clpobtvoceecadeirante": null,
              "bp_clpobtnecessidadedeuhadaptada": null,
              "cdhu_clpocosistemaorigem@OData.Community.Display.V1.FormattedValue": "Gest\u00E3o de Carteira",
              "cdhu_clpocosistemaorigem": 5,
              "bp_clpo_pl_sexodoconjugeatual": null,
              "bp_clpo_mn_rendadoconjugeatual": null,
              "cdhu_clpovlvalorrendaatual@OData.Community.Display.V1.FormattedValue": "R$ 1.500,00",
              "cdhu_clpovlvalorrendaatual": 1500.0000,
              "bp_cdhu_clponmufdenascimentoconjuge": null,
              "_cdhu_idunidadehabitacionalid_value@OData.Community.Display.V1.FormattedValue": "3282183",
              "_cdhu_idunidadehabitacionalid_value": "1b392563-6e19-4aa5-9ad5-b692b6a190e5",
              "_bp_empreendimentoinscricaoleadid_value": null,
              "cdhu_data_inicio_auxilio_moradia@OData.Community.Display.V1.FormattedValue": "04/05/2023",
              "cdhu_data_inicio_auxilio_moradia": "2023-05-04T03:00:00Z",
              "bp_clpovloutrarendafamiliar@OData.Community.Display.V1.FormattedValue": "R$ 1.723,22",
              "bp_clpovloutrarendafamiliar": 1723.2200000000,
              "_bp_clp_lk_conjugeatual_value": null,
              "_bp_clp_lk_companheiroatual_value": null,
              "bp_clp_bt_uniaoestavelatual@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clp_bt_uniaoestavelatual": false,
              "bp_clp_bt_confirmacaouniaoestavelatual@OData.Community.Display.V1.FormattedValue": "N\u00E3o",
              "bp_clp_bt_confirmacaouniaoestavelatual": false,
              "statecode@OData.Community.Display.V1.FormattedValue": "Aberta",
              "statecode": 0,
              "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "Real",
              "_transactioncurrencyid_value": "c09c1735-b749-e611-80e6-2c59e53a159c",
              "address1_composite": "Jos\u00E9 Mascarenhas, 10\r\nVila Matilde\r\nSAO PAULO - SP\r\nBRASIL\r\n03515-000",
              "cdhu_lead_contact": [
                {
                  "@odata.etag": "W/\u00227088984986\u0022",
                  "contactid": "767c84cf-ec54-4db9-8784-6929027914cb",
                  "_cdhu_idclientepotencialcdhuid_value@OData.Community.Display.V1.FormattedValue": "AARAO LUIZ DA SILVA",
                  "_cdhu_idclientepotencialcdhuid_value": "2c3d8fd8-c214-416f-afb2-e700b86c9c16"
                }
              ],
              "cdhu_lead_contact@odata.nextLink": "https://cdhucrmdev.api.crm2.dynamics.com/api/data/v9.0/leads(2c3d8fd8-c214-416f-afb2-e700b86c9c16)/cdhu_lead_contact?$select=contactid"
            }
          ]
        }
        """;
}

