//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cblx.Blocks.Analyzers.Endpoints {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cblx.Blocks.Analyzers.Endpoints.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace &apos;{0}&apos; with &apos;{1}&apos;.
        /// </summary>
        internal static string CBLX0001CodeFixTitle {
            get {
                return ResourceManager.GetString("CBLX0001CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All classes inheriting from EndpointBase should implement an internal static method named ExecuteAsync..
        /// </summary>
        internal static string CBLX0001Description {
            get {
                return ResourceManager.GetString("CBLX0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; should contain an internal static method named &apos;ExecuteAsync&apos;..
        /// </summary>
        internal static string CBLX0001MessageFormat {
            get {
                return ResourceManager.GetString("CBLX0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint should contain ExecuteAsync method.
        /// </summary>
        internal static string CBLX0001Title {
            get {
                return ResourceManager.GetString("CBLX0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to static method.
        /// </summary>
        internal static string CBLX0002CodeFixTitle {
            get {
                return ResourceManager.GetString("CBLX0002CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All classes inheriting from EndpointBase should implement an internal static method named ExecuteAsync..
        /// </summary>
        internal static string CBLX0002Description {
            get {
                return ResourceManager.GetString("CBLX0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; should be static..
        /// </summary>
        internal static string CBLX0002MessageFormat {
            get {
                return ResourceManager.GetString("CBLX0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecuteAsync method should be static.
        /// </summary>
        internal static string CBLX0002Title {
            get {
                return ResourceManager.GetString("CBLX0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to internal method.
        /// </summary>
        internal static string CBLX0003CodeFixTitle {
            get {
                return ResourceManager.GetString("CBLX0003CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All classes inheriting from EndpointBase should implement an internal static method named ExecuteAsync..
        /// </summary>
        internal static string CBLX0003Description {
            get {
                return ResourceManager.GetString("CBLX0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; should be internal..
        /// </summary>
        internal static string CBLX0003MessageFormat {
            get {
                return ResourceManager.GetString("CBLX0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecuteAsync method should be internal.
        /// </summary>
        internal static string CBLX0003Title {
            get {
                return ResourceManager.GetString("CBLX0003Title", resourceCulture);
            }
        }
    }
}
